import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
	params: Promise<{
		locale: string;
	}>;
}

export default async function LocaleLayout({
	children,
	params,
}: Readonly<RootLayoutProps>) {
	const locale = (await params).locale;

	if (!routing.locales.includes(locale as "tr" | "en")) {
		notFound();
	}

	setRequestLocale(locale);
	const messages = await getMessages({ locale });

	return (
		<NextIntlClientProvider locale={locale} messages={messages}>
			<Header />
			{children}
			<Footer />
		</NextIntlClientProvider>
	);
}
